service: passgen-server
provider:
  name: aws
  runtime: nodejs14.x
custom:
  writeEnvVars:
    NODE_ENV: ${file(.env.yml):${opt:stage, 'dev'}.NODE_ENV}
    DATABASE_URL: ${file(.env.yml):${opt:stage, 'dev'}.MONGODB_URI}
plugins:
  - serverless-plugin-write-env-vars
functions:
  api:
    handler: lambda.handler
    events:
    - http:
        path: "{proxy+}"
        method: get
    - http:
        path: "{proxy+}"
        method: post